remote_theme:  mmistakes/minimal-mistakes 
#remote_theme: pmarsceill/just-the-docs
minimal_mistakes_skin: "neon"
title: "Taming Penguins"
description: "Tech, Linux, DIY"

# Syntax highlighting engine
highlighter: rouge

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/"]

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false