# This is a comment.
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: dark

# Syntax highlighting engine
highlighter: rouge

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/"]

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false